spring:
  main:
    web-application-type: none

gateway:
  port: 8080
  max-content-length: 1048576
  pooled-allocator-enabled: true
  health-endpoint-enabled: true
  metrics-endpoint-enabled: true
  management-allowed-client-ips:
    - 127.0.0.1
    - ::1
  max-pending-per-route: 1024
  routes:
    - route-id: route-main
      priority: 100
      match-type: PREFIX
      path: /api/
      host-rewrite-mode: REWRITE
      upstream:
        scheme: http
        host: 127.0.0.1
        port: 9001
        connect-timeout-ms: 1000
        read-timeout-ms: 1000
        write-timeout-ms: 1000
