name: Java CI with Maven

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Check Code Format
      run: mvn formatter:validate
        
    - name: Code Style Check
      run: mvn checkstyle:check
        
    - name: Run Tests
      run: mvn test
        
    - name: Generate Coverage Report
      run: mvn jacoco:report
        
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: '**/target/site/jacoco'
        
    - name: Build Package
      run: mvn -B package
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gateway-artifacts
        path: |
          **/target/*.jar
          !**/target/original-*.jar

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/target/surefire-reports' 